version: '2'
services:
  
  db:
    container_name: odoo11_db
    image: postgres:10
    ports:
      - "5060:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres  
    volumes:
      - postgres-data:/var/lib/postgresql/11/data     
    restart: always
 
  web:
    container_name: odoo11_web
    image: odoo:11.0
    depends_on:
      - db
    ports:
      - "11000:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always

volumes:
  db:
  web:
  postgres-data:
