version: '2'
services:
  
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/11/data     
    restart: always
 
  web:
    image: odoo:11.0
    depends_on:
      - db
    ports:
      - "11000:8069"
    tty: true
    command: -- --dev=reload
    #command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5060:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always

volumes:
  db:
  web:
  postgres-data:
